#Used by the bot to login to pokemon-vortex
player:
  username: ''
  password: ''

#Based on rarity type, make groups (with arbitrary names) of properties to catch pokemon on, or leave empty to catch any pokemon from that rarity
#properties:
# caught:
#   - 0 (for anything you havent caught before)
#   - 1 (if caught but not this season)
#   - 2 (if caught this season)

# special:
#   - Shiny
#   - Shadow
#   - Mystic
#   - Dark
#   - Metallic

# name:
#   - Any name of a pokemon from that rarity type

pokemon:
  COMMON:
    case1:
        caught:
          - 0
    case2:
        special:
          - Shiny
  RARE:
  LEGENDARY:
  ULTRA:


threshold:
  Poké Ball: 20
  Great Ball: 10
  Ultra Ball: 10

mode: catch