#Used by the bot to login to pokemon-vortex
player:
  username: ''
  password: ''

#Based on rarity type, make groups (with arbitrary names) of properties to catch pokemon on, or leave empty to catch any pokemon from that rarity
#properties:
# caught:
#   - 0 (for anything you havent caught before)
#   - 1 (if caught but not this season)
#   - 2 (if caught this season)

# special:
#   - Shiny
#   - Shadow
#   - Mystic
#   - Dark
#   - Metallic

# name:
#   - Any name of a pokemon from that rarity type

pokemon:
  COMMON:
    not in collection:
        caught:
          - 0
    i like shinies:
        special:
          - Shiny
  RARE:
  LEGENDARY:
  ULTRA:

#Minimum threshold of every normal balltype (poke, great and ultra) is 3
#Master and Beast arent supported
#Beast threshold is unused, if UB is encountered with no Beast Balls in inventory, program will exit
restock:
  Poké Ball:
    min: 20
    goal: 50
  Great Ball:
    min: 10
    goal: 20
  Ultra Ball:
    min: 10
    goal: 20

mode: catch